### ISSUE TITLE
X-Forwarded-* / Forwarded headers

### ISSUE THREAD

**Issue by thekid** [xp-forge/web#27]
Resources:

* https://github.com/spring-projects/spring-boot/issues/2603
* https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
* http://httpd.apache.org/docs/trunk/mod/mod_proxy.html#x-headers

**Comment by thekid** [comment]
Unsure whether this should be baked in our whether it should be shipped e.g. as `web.filters.BehindProxy`

**Comment by thekid** [comment]
```php
$rewrite= new class($base) implements Filter {
  private $base;

  public function __construct($base= '/') {
    $this->base= $base;
  }

  public function filter($request, $response, $invocation) {
    if ($forwarded= $request->header('X-Forwarded-Host')) {
      $request->rewrite($request->uri()
        ->using()
        ->scheme($request->header('X-Forwarded-Proto') ?? 'https')
        ->host($forwarded)
        ->port($request->header('X-Forwarded-Port') ?? 443)
        ->path($this->base.$request->uri()->path())
        ->create()
      );
    }

    return $invocation->proceed($request, $response);
  }
};
```

**Comment by thekid** [comment]
* [ ] X-Forwarded-Proto seems to be missing in most cases... the default value 'https' cannot be safely assumed and should be configurable from the outside.
* [ ] Default ports for HTTP and HTTPS should be omitted

**Comment by thekid** [comment]
These headers contain user input, and cannot be trusted.

**Comment by mcarbonneaux** [comment]
on some framework we use ip list (reverse proxy ip list that adding this header) that to trust this header.

**Comment by thekid** [comment]
The solution I've found is to use this as described in #41:

```php
$filter= new BehindProxy(['https://service.example.com/' => '/']);
```

The thought is: If we're supplying whitelists and manually configuring this, we might as well configure the URI part to remove. Instead of first trusting a reverse proxy and then reading the URI from the header, we just use a simple string replacement. This also works when the remote IP / IP range changes.
