### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by thekid** [xp-forge/web#36]
Last prerequisite for a 1.0:

* `$req->files()`?
* `(new FileUpload($req))->files();`

**Comment by thekid** [comment]
See e.g. http://commons.apache.org/proper/commons-fileupload/streaming.html

**Comment by thekid** [comment]
```php
$upload= new FileUpload($req);
foreach ($upload->files() as $file) {
  Console::writeLine($file, ' => ', addcslashes(Streams::readAll($file), "\0..\17!\177..\377"));
}
```

**Comment by thekid** [comment]
In GoLang:

https://golang.org/pkg/net/http/#Request.ParseMultipartForm

> ParseMultipartForm parses a request body as multipart/form-data. The whole request body is parsed and up to a total of maxMemory bytes of its file parts are stored in memory, with the remainder stored on disk in temporary files. ParseMultipartForm calls ParseForm if necessary. After one call to ParseMultipartForm, subsequent calls have no effect.

**Comment by johannes85** [comment]
@thekid Anithing new here? Can I provide help in any way shape or form.

**Comment by thekid** [comment]
@johannes85 Here's an early draft:

```php
<?php

use io\File;
use util\cmd\Console;
use web\{Application, MultiPart};

// See https://medium.com/@petehouston/upload-files-with-curl-93064dcccc76
class Upload extends Application {

  public function routes() {
    return [
      '/' => function($req, $res) {
        Console::writeLine($req->headers());

        $multipart= new MultiPart($req);
        if ($multipart->present()) {
          foreach ($multipart->parts() as $i => $part) {
            Console::writeLine($part->name(), ': ', $part->headers());
            if ($part->isFile()) {

              $out= new File($part->filename());
              $out->open(File::WRITE);
              while ($bytes= $part->read()) {
                Console::write('+', strlen($bytes));
                $out->write($bytes);
              }
              $out->close();
              Console::writeLine(' > ', $out);
            } else {
              Console::writeLine($part->value());
            }
          }
        }

        $res->answer(200, 'OK');
        $res->send('Accepted', 'text/plain');
      }
    ];
  }
}
```

The classes can be found here: https://gist.github.com/thekid/e1d6a171ced83f801c398093c061a423

*No support for development webserver yet!*

**Comment by thekid** [comment]
Merged #62 as prerequisite for parsing `Content-Disposition` handlers.

**Comment by thekid** [comment]
The general architecture of  the implementation:

* [ ] A new method `parts()` will be added to `web.io.Input` and its implementation
* [ ] Inside `xp.web.SAPI`, this will access the superglobal `$_FILES`
* [ ] Inside the standalone server implementation, it will use a `MultiPart` body parser
* [ ] It will yield names and one of the following:
  * `web.io.Part` - a part without a file, usually a parameter (*never yielded by PHP SAPIs, these have been processed before*)
  * `web.io.FileStream` - the part is streamed
  * `web.io.FileUpload` - the upload is stored in PHP's `upload_tmp_dir`
  * `web.io.Partial` - the upload has errors (see https://www.php.net/manual/en/features.file-upload.errors.php)

These will be accessible by `web.Request::files()`, a higher-level method which will take care of merging request parameters.

**Comment by thekid** [comment]
Handling `Expect: 100-continue` for uploads should be part of this. Curl uses this when uploading files.

```php
// See https://tools.ietf.org/html/rfc7231#section-6.2.1
// and https://tools.ietf.org/html/rfc7231#section-5.1.1
//
// Answer with intermediate status code 100 to have client proceed
// or e.g. 405 (Method not allowed) to cancel the upload.
if ('100-continue' === $req->header('Expect')) {
  $res->write("HTTP/1.0 100 Continue\r\n\r\n");
}
```

Not: 100 is not the only status code used with intermediary responses, see https://tools.ietf.org/html/rfc8297
