### ISSUE TITLE
Logging to Console isn't working in dev mode on Linux

### ISSUE THREAD

**Issue by johannes85** [xp-forge/web#50]
When I use the ConsoleAppender to write an log message to the console it only works when I disable the develop mode of the server.

It seems that it has someting to do with the stream the ConsoleAppender is writing to:
It writes to STDERR via ```Console::$err```, when I change it to ```Console::$out``` it works.

**Comment by johannes85** [comment]
It is coused by redirecting STDERR of the process to /dev/null:
https://github.com/xp-forge/web/blob/89381d0b4d8093bb54afd55008706e245831d44d/src/main/php/xp/web/srv/Develop.class.php#L85

**Comment by thekid** [comment]
`['file', $nul, 'w']` was added to suppress the PHP development server's own logfile

**Comment by thekid** [comment]
Can be fixed by changing where `ConsoleAppender` logs by default, see https://github.com/xp-framework/logging/pull/10

**Comment by thekid** [comment]
Fixed if you upgrade the logger to https://github.com/xp-framework/logging/releases/tag/v9.0.0
