### ISSUE TITLE
Isn't working with xp-framework/networking 9 since version 2.8

### ISSUE THREAD

**Issue by johannes85** [xp-forge/web#79]
When I use "web" with an older (9.x) neworking version, the application hangs and produces 100% CPU load when calling it via http.

My environment is:
PHP 7.3
XP Core 9

The issue can be reproduced with this Gist, by running its docker container:
https://gist.github.com/johannes85/9ba23b890355c2424a8c18359780d7d1
```docker build --tag xpwebtest . && docker run --rm -it xpwebtest```

**Comment by thekid** [comment]
With PHP 7.3, I can reproduce this - the server starts but CURL never gets any response.

I get the following with PHP 8, this may indicate where the problem roots from:

```bash
$ xp web Service
Uncaught exception: Error (Undefined constant "peer\server\SOMAXCONN")
```

**Comment by thekid** [comment]
This was fixed in 10.0.1:

> ## 10.0.1 / 2020-07-11
>
> * Fixed issue #14: Discover SOMAXCONN programmatically if not defined
>  (@thekid)

**Comment by thekid** [comment]
Workaround found and verified to be working for XP9 with both PHP 7 and PHP 8.

**Comment by thekid** [comment]
Fix included in https://github.com/xp-forge/web/releases/tag/v2.11.0

**Comment by thekid** [comment]
> PHP 7.3

Though unrelated to this issue: Keep in mind active support for this PHP version has ended more than half a year ago:

https://www.php.net/supported-versions.php
